"""Subclass of base_frame, which is generated by wxFormBuilder."""

import wx
from modules.ui.ui_app import base_frame

# Implementing base_frame
class ui_appbase_frame(base_frame):
	def __init__( self, parent ):
		super().__init__(parent )

